name: x_clone_flutter
description: "X Cone App with Flutter"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  dio: ^5.6.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^4.2.1
  google_fonts: ^6.2.1
  hidable: ^1.0.6
  image_picker: ^1.1.2
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  uuid: ^4.4.2
  vector_graphics: ^1.1.11+1
  vector_graphics_compiler: ^1.1.11+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.2
  build_runner: ^2.4.12
  custom_lint: ^0.6.5
  riverpod_lint: ^2.3.12

flutter:
  uses-material-design: true
  assets:
    # Regular assets
    - path: assets/default_image.png
    - path: assets/default_avatar.png
    # SVGs to be transformed
    - path: assets/icon_comment.svg
      transformers:
        - package: vector_graphics_compiler
    - path: assets/icon_heart_blue.svg
      transformers:
        - package: vector_graphics_compiler
    - path: assets/icon_heart_red.svg
      transformers:
        - package: vector_graphics_compiler
    - path: assets/icon_info.svg
      transformers:
        - package: vector_graphics_compiler
    - path: assets/icon_link.svg
      transformers:
        - package: vector_graphics_compiler
    - path: assets/icon_verified.svg
      transformers:
        - package: vector_graphics_compiler
    - path: assets/icon_x.svg
      transformers:
        - package: vector_graphics_compiler